### ISSUE TITLE
Include ORCID identifiers in authors block

### ISSUE THREAD

**Issue by arfon** [arfon/metamatter#3]
Ideally we should search the ORCID API to see if we can match the GitHub email address with an ORCID profile.

**Comment by arfon** [comment]
@amontenegro @lpaglione - would you be able to provide any insights here? As far as I can tell it's not possible to search the public ORCID API for an email address.

**Comment by rcpeters** [comment]
Hi @arfon, it isn't practical to lookup email address as most are marked private. Should we set up a call to go over your goals and possible options? My direct email is r.peters@orcid.org

**Comment by arfon** [comment]
That would be great! I'll send you an email.
