### ISSUE TITLE
Smarter DOI detection

### ISSUE THREAD

**Issue by arfon** [arfon/metamatter#4]
Currently we only return a DOI if there's a Zenodo badge in the README. We should search data archives to find references to the GitHub repository address rather than just rely upon the author having put a badge in the README.

**Comment by arfon** [comment]
@mfenner - any thoughts on this?

**Comment by mfenner** [comment]
One place to start is to search the DataCite metadata for a Github repo URL in the `relatedIdentifier` field. Use Zenodo examples to see how this looks like, but I could also provide a sample API call.

**Comment by mfenner** [comment]
Related to this: https://github.com/zenodo/zenodo/issues/354

**Comment by arfon** [comment]
>  but I could also provide a sample API call.

:+1: that would be most welcome :smile:

**Comment by mfenner** [comment]
Here is some sample code: https://github.com/lagotto/lagotto/blob/master/app/models/sources/datacite.rb

A sample API call for a specific Github repo: http://search.datacite.org/api?q=relatedIdentifier:https://github.com/articlemetrics/lagotto&fl=doi,creator,title,publisher,publicationYear,resourceTypeGeneral,datacentre,datacentre_symbol,prefix,relatedIdentifier&fq=is_active:true&fq=has_metadata:true&rows=1000&wt=json

Use Solr syntax to modify, e.g. a wildcard search for any Github URL.

**Comment by arfon** [comment]
Awesome. Thanks @mfenner.
